### ISSUE TITLE
CSS User Input Form Layout

### ISSUE THREAD

**Issue by psych0sykes** [ccollins1544/project1#11]
## CSS User Input Form

The GUI needs to be *nice*.

## Tasks

- [ ] Create and link stylesheet
- [ ] match the form to the layout example image in the assets folder

**Comment by ccollins1544** [comment]
`:root {
  --accent-text: #0092CA;
  --primary-menu-background: #52616B;
  --secondary-menu-text: #F0F5F9;
  --secondary-menu-background: rgba(0, 0, 0, 0.8);
  --body-text: #1E2022;
  --body-background: #F0F5F9;
  --button-text: #C9D6Df;
  --button-background: #1E2022;
  --cool-red: #E9290F;
  --footer-hover-text: rgba(233, 41, 15, .9);
}`
